services:
  build-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: sh
    tty: true
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "5556:5555"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=3312
    restart: always
    networks:
      - db-network

networks:
  db-network:
    external:
      name: db-network
