version: '3.8'
services:
  postgres-test-api:
    image: postgres:16.3-alpine3.19
    container_name: postgres-test-api
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DATA}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file: .env
    ports:
        - "3312:5432"
    volumes:
      - ${SERVICE_DATA}/db/postgres13:/var/lib/postgresql/data/
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
    name: db-network
